### ISSUE TITLE
ユーザのモチベーションをキープする方法を考える

### ISSUE THREAD

**Issue by gaku-jay** [Super-Spork/something-awesome#4]
コミュニティで活動、英語×ITで活動するためのモチベーションが保てない（ケツを叩いて欲しい）ユーザを助ける機能を開発したい
→ケツを叩く方法を考える。Issueにコメント。11/21土曜日まで

**Comment by hitogen** [comment]
同調圧力（同じな目標のユーザーの進捗・成果を見る時）が有効と思うのだが、大学受験とかと違って期限が決まっていないから焦るのかは微妙気がする。

**Comment by gaku-jay** [comment]
-  (@hitogen に追加）同期みたいな概念あれば焦るかもね。同じ日に頑張ろうと決めた人が自分より進捗があったらモチベあがる気がする。
- Gitの草生やす機能みると結構やる気出るから、草生やす機能欲しい。自分と他人の成果が可視化されるのは嬉しい。
あとエンジニアだから、親しみやすいのでは？単語とかフレーズのCommitとか？笑　他人の単語RepoをPullできるみたいな笑
- Topページにユーザのサクセスストーリとかランキングとか載せたらやる気でそう。
- 公開ToDoリスト

**Comment by ghibney** [comment]
- 目標（希望する職種で海外移住や海外の企業で就職するためなど）を設定してもらい、何が足りないかを知るために簡単なテストのようなものを受けてもらう。テストの結果から、簡易的に目標達成実現度を算出する（A判定、B判定みたいな感じ）
  学歴、今までのエンジニアとしての経歴の記載、英語能力の簡単なテスト（weblioの英語テストとか？）を受けてもらって、海外移住のVISA申請の要求条件や、企業オファーの統計などから、技術的、英語能力的に何が足りていないかを可視化

- ユーザを目標達成実現度ごとにグループ振り分けする

- 目標が何で、それまでに何をすべきかのTodoリストを作成してもらい、グループ内で共有する
  
- todoリストの進捗状況をもとに、誰が頑張っているかをリーダーボードに載せる

**Comment by gaku-jay** [comment]
> * (@hitogen に追加）同期みたいな概念あれば焦るかもね。同じ日に頑張ろうと決めた人が自分より進捗があったらモチベあがる気がする。
やj
> * Gitの草生やす機能みると結構やる気出るから、草生やす機能欲しい。自分と他人の成果が可視化されるのは嬉しい。
>   あとエンジニアだから、親しみやすいのでは？単語とかフレーズのCommitとか？笑　他人の単語RepoをPullできるみたいな笑
> * Topページにユーザのサクセスストーリとかランキングとか載せたらやる気でそう。
> * 公開ToDoリスト

**Comment by gaku-jay** [comment]
### アイディア
目標設定
目標（希望する職種で海外移住や海外の企業で就職するためなど）を設定してもらい、何が足りないかを知るために簡単なテストORアンケートのようなものを受けてもらう。テストの結果から、簡易的に目標達成実現度を算出する（A判定、B判定みたいな感じ）
学歴、今までのエンジニアとしての経歴の記載、英語能力の簡単なテスト（weblioの英語テストとか？）を受けてもらって、海外移住のVISA申請の要求条件や、企業オファーの統計などから、技術的、英語能力的に何が足りていないか

Todoリスト
毎日簡単なタスクで進捗がすぐ見られるもの（ゲームみたいな感覚）をリマインドすればコツコツやれる気がする。（例えばStackoverflowの質問を英語で答える等）
todoリストの進捗状況をもとに、誰が頑張っているかをリーダーボードに載せる
公開ToDoリスト

同調圧力

同調圧力（同じな目標のユーザーの進捗・成果を見る時）が有効と思うのだが、大学受験とかと違って期限が決まっていないから焦るのかは微妙気がする。
(@hitogen に追加）同期みたいな概念あれば焦るかもね。同じ日に頑張ろうと決めた人が自分より進捗があったらモチベあがる気がする。
ユーザを目標達成実現度ごとにグループ振り分けする
例　「レベル１から●人がレベル２に上がりました。」
Topページにユーザのサクセスストーリとかランキングとか載せたらやる気でそう。
ユーザを目標達成実現度ごとにグループ振り分けする
目標が何で、それまでに何をすべきかのTodoリストを作成してもらい、グループ内で共有する
Gitの草生やす機能みると結構やる気出るから、草生やす機能欲しい。自分と他人の成果が可視化されるのは嬉しい。
あとエンジニアだから、親しみやすいのでは？単語とかフレーズのCommitとか？笑　他人の単語RepoをPullできるみたいな笑

イベント開催
100 days of XXX みたいなチャレンジを開催する
